{"links": {"self": {"href": "data/repositories/osrf/srcsim/issues/210/comments/37361140.json"}, "html": {"href": "#!/osrf/srcsim/issues/210#comment-37361140"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/srcsim/issues/210.json"}}, "type": "issue", "id": 210, "repository": {"links": {"self": {"href": "data/repositories/osrf/srcsim.json"}, "html": {"href": "#!/osrf/srcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{c41021d9-0217-4628-999d-7f8d82f98dcb}ts=c_plus_plus"}}, "type": "repository", "name": "srcsim", "full_name": "osrf/srcsim", "uuid": "{c41021d9-0217-4628-999d-7f8d82f98dcb}"}, "title": "Harness after advancing checkpoint can fail to exit state 4"}, "content": {"raw": "I commented on the commit as well, but this reproduces easily in the 2ms branch, and instrumenting the value used in the commit, it seems as though changing the force from 500 to 450 would solve the problem.", "markup": "markdown", "html": "<p>I commented on the commit as well, but this reproduces easily in the 2ms branch, and instrumenting the value used in the commit, it seems as though changing the force from 500 to 450 would solve the problem.</p>", "type": "rendered"}, "created_on": "2017-06-04T15:09:26.457744+00:00", "user": {"display_name": "Jeremy White", "uuid": "{abab48b0-35b1-4102-8373-e88a492c5294}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Babab48b0-35b1-4102-8373-e88a492c5294%7D"}, "html": {"href": "https://bitbucket.org/%7Babab48b0-35b1-4102-8373-e88a492c5294%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2764d3b5adf560de71f57e48a30550bad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJW-3.png"}}, "nickname": "knitfoo", "type": "user", "account_id": "557058:5de786d6-615c-44ef-8e12-f079efa38357"}, "updated_on": null, "type": "issue_comment", "id": 37361140}